### ISSUE TITLE
Getting list of contacts but not the chats/messages

### ISSUE THREAD

**Issue by AJCastello** [krthr/whatsapp-client#4]
Hi, thank you for this! After done the installation, everything works: reading the qr code, creating a session, loading the contacts, all good... but no messages are loaded, this is what i got in the console.

> {
>   msg: [
>     'response',
>     { type: 'chat' },
>     [
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array], [Array], [Array], [Array], [Array], [Array],
>       [Array], [Array],
>       ... 215 more items
>     ]
>   ]
> }
> RangeError: index out of range: 257 + 10 > 257
>     at indexOutOfRange (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:13:12)
>     at BufferReader.read_uint32 [as uint32] (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:98:19)
>     at Type.Message$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:6:11)
>     at Type.decode_setup [as decode] (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\type.js:507:25)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:12:22)
>     at Type.decode_setup [as decode] (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\type.js:507:25)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
> Error: invalid wire type 7 at offset 81
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:368:22)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
> Error: invalid wire type 7 at offset 81
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:368:22)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
> Error: invalid wire type 7 at offset 81
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:368:22)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
> Error: invalid wire type 7 at offset 81
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:368:22)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
> Error: invalid wire type 7 at offset 81
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:368:22)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
> Error: invalid wire type 7 at offset 81
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:368:22)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
> RangeError: index out of range: 224 + 4263 > 479
>     at indexOutOfRange (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:13:12)
>     at BufferReader.skip (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:338:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:364:18)
>     at Type.AudioMessage$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:45:5)
>     at Type.decode_setup [as decode] (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\type.js:507:25)
>     at Type.Message$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:30:27)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:12:22)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
> Error: invalid wire type 6 at offset 179
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
>     at Receiver.emit (events.js:310:20)
> Error: invalid wire type 7 at offset 81
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:368:22)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
> RangeError: index out of range: 273 + 10 > 273
>     at indexOutOfRange (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:13:12)
>     at BufferReader.read_uint32 [as uint32] (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:98:19)
>     at Type.Message$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:6:11)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:12:22)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
> Error: invalid wire type 7 at offset 81
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:368:22)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
> Error: invalid wire type 7 at offset 81
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:368:22)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
> Error: invalid wire type 7 at offset 81
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:368:22)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
> Error: invalid wire type 4 at offset 109
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
>     at Receiver.emit (events.js:310:20)
> Error: invalid wire type 7 at offset 81
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:377:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:368:22)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
> RangeError: index out of range: 105 + 854640323 > 106
>     at indexOutOfRange (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:13:12)
>     at BufferReader.skip (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:338:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:364:18)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
> RangeError: index out of range: 128 + 10 > 128
>     at indexOutOfRange (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:13:12)
>     at BufferReader.read_uint32 [as uint32] (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:98:19)
>     at BufferReader.Reader.skipType (C:\xampp\htdocs\waclient\backend\node_modules\protobufjs\src\reader.js:367:37)
>     at Type.WebMessageInfo$decode [as decode] (eval at Codegen (C:\xampp\htdocs\waclient\backend\node_modules\@protobufjs\codegen\index.js:50:33), <anonymous>:82:5)
>     at Object.decode (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_defines.js:279:27)
>     at whatsappReadMessageArray (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:325:64)
>     at whatsappReadBinary (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\whatsapp_reader.js:336:15)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:117:21)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
> SyntaxError: Unexpected token ! in JSON at position 0
>     at JSON.parse (<anonymous>)
>     at WhatsAppService.handleMessage (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:61:27)
>     at WebSocket.<anonymous> (C:\xampp\htdocs\waclient\backend\src\services\whatsapp\index.js:270:41)
>     at WebSocket.emit (events.js:310:20)
>     at Receiver.receiverOnMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\websocket.js:800:20)
>     at Receiver.emit (events.js:310:20)
>     at Receiver.dataMessage (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\receiver.js:436:14)
>     at Receiver.getData (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\receiver.js:366:17)
>     at Receiver.startLoop (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\receiver.js:142:22)
>     at Receiver._write (C:\xampp\htdocs\waclient\backend\node_modules\ws\lib\receiver.js:77:10)
> WhatsApp closed the connection oslYjwxMgpmsPd9uO5Tpew==
> ✌ Bye oslYjwxMgpmsPd9uO5Tpew==

Is that about changes on the whatsapp web selectors or what?

**Comment by krthr** [comment]
Hi! Thank you for your interest on this forgotten repository. Actually, I recommend you to take a look on the following projects:

- https://github.com/sigalor/whatsapp-web-reveng
- https://github.com/adiwajshing/Baileys
- https://github.com/ndunks/WaJs

**Comment by AJCastello** [comment]
Thank you very much! Baileys version is working fine here.
